# Generated by Django 4.1.5 on 2023-07-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='theblog.category'),
        ),
    ]
